spring:
  #邮件相关
  mail:
    host: smtp.qq.com
    username: 3467332725@qq.com
    password: oqtclvifkfmochgf
  rabbitmq:
    #消息中间件的地址
    addresses: 8.137.23.208
    username: hero
    password: 123456
    virtual-host: /test
  security:
    #security拦截器的默认优先级，默认为-100
    filter:
      order: -100
    jwt:
      # 加密秘钥
      key: abcdefghijk
      #过期时间
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/monitor
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
